version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
    container_name: laravel_api
    volumes:
      - ./backend:/var/www
    networks:
      - app-network

  # Web Server (Nginx) để chạy Laravel
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - app-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
    container_name: react_app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  # Database Service
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: thuy_hai_san
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge